# Generated by Django 3.0.4 on 2020-05-03 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('actors', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('paymentBy', models.CharField(max_length=300)),
                ('whichExpense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.Expense')),
            ],
        ),
    ]
