# Generated by Django 3.0.4 on 2020-05-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
